Ferremas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ferremas_APP.urls')),
]

Ferremas_APP/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('construccion/', views.construccion, name='construccion'),
    path('herramientas/', views.herramientas, name='herramientas'),
    path('hogar/', views.hogar, name='hogar'),
    path('piso_y_pared/', views.piso_y_pared, name='piso_y_pared'),
    path('detalle/<int:producto_id>/', views.detalle, name='detalle'), 
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'), 
    path('eliminar_del_carrito/<int:producto_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'), 
    path('ver_carrito/', views.ver_carrito, name='ver_carrito'),
    path('actualizar_carrito/<int:producto_id>/', views.actualizar_carrito, name='actualizar_carrito'),
    path('carrito/', views.carrito, name='carrito'), 
    path('iniciar_pago/', views.iniciar_pago, name='iniciar_pago'),
    path('webpay_confirmacion/', views.webpay_confirmacion, name='webpay_confirmacion'),
    path('formulario_datos/', views.formulario_datos, name='formulario_datos'),
    path('registro/', views.registro, name='registro'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ferremas_APP/models.py
from django.db import models
from django.contrib.auth.models import User

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    detalleCompleto = models.TextField(default='')
    especificaciones = models.CharField(max_length=100, null=True, blank=True)
    lista1 = models.CharField(max_length=100, null=True, blank=True)
    lista2 = models.CharField(max_length=100, null=True, blank=True)
    lista3 = models.CharField(max_length=100, null=True, blank=True)
    lista4 = models.CharField(max_length=100, null=True, blank=True)
    lista5 = models.CharField(max_length=100, null=True, blank=True)
    incluye = models.CharField(max_length=100, null=True, blank=True)
    lista6 = models.CharField(max_length=100, null=True, blank=True)
    lista7 = models.CharField(max_length=100, null=True, blank=True)
    lista8 = models.CharField(max_length=100, null=True, blank=True)
    lista9 = models.CharField(max_length=100, null=True, blank=True)
    lista10 = models.CharField(max_length=100, null=True, blank=True)
    precioOferta = models.DecimalField(max_digits=8, decimal_places=2 , null=True, blank=True)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    stock = models.IntegerField()
    imagen = models.ImageField(upload_to='productos', null=True, blank=True)
    

    def __str__(self):
        return self.nombre
    
class Carrito(models.Model):
    sesion_id = models.CharField(max_length=100)

class CarritoProducto(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

class Pedido(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)  # Opcional
    TIPO_ENTREGA_CHOICES = [
        ('RT', 'Retiro en Tienda'),
        ('DD', 'Despacho a Domicilio')
    ]
    
    tipo_entrega = models.CharField(max_length=2, choices=TIPO_ENTREGA_CHOICES, default='RT')
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    email = models.EmailField()
    numero_pedido = models.CharField(max_length=10, unique=True)
    datos_completados = models.BooleanField(default=False)  # Nuevo campo para indicar si los datos del cliente han sido completados

    def __str__(self):
        return f'Pedido {self.numero_pedido}'

    def get_nombre_completo(self):
        return f'{self.nombre} {self.apellidos}'

    def get_email(self):
        return self.email
    
class Transaccion(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    token = models.CharField(max_length=100)
    buy_order = models.CharField(max_length=100)
    session_id = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=50)
    authorization_code = models.CharField(max_length=50, null=True, blank=True)
    payment_type_code = models.CharField(max_length=50, null=True, blank=True)
    response_code = models.CharField(max_length=50, null=True, blank=True)
    transaction_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Transaccion {self.token} - {self.status}'

    def get_cliente_nombre(self):
        return self.pedido.nombre

    def get_cliente_apellidos(self):
        return self.pedido.apellidos

    def get_cliente_email(self):
        return self.pedido.email

    get_cliente_nombre.short_description = 'Nombre'
    get_cliente_apellidos.short_description = 'Apellidos'
    get_cliente_email.short_description = 'Correo Electrónico'

class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return f'Perfil de {self.user.username}'

Ferremas_APP/views.py
from django.shortcuts import get_object_or_404, render, redirect

from Ferremas_APP.templatetags.custom_filters import formato_moneda
from .models import Producto, Carrito, CarritoProducto, Pedido, Transaccion, PerfilUsuario
from django.http import JsonResponse, Http404
from django.views.decorators.http import require_POST
import json
from decimal import Decimal
from django.urls import reverse
from transbank.webpay.webpay_plus.transaction import Transaction, WebpayOptions
from transbank.common.integration_type import IntegrationType
from django.conf import settings
from transbank.error.transbank_error import TransbankError
import random
from .forms import PedidoForm, RegistroUsuarioForm, LoginUsuarioForm
from .utils import enviar_correo_confirmacion, obtener_tipo_cambio, SERIES_CODIGOS
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required




def index(request):
    productos = Producto.objects.all()
    return render(request, 'index.html', {'productos': productos})

@require_POST
def agregar_al_carrito(request, producto_id):
    if request.method == 'POST':
        csrf_token = request.POST.get('csrfmiddlewaretoken')
        if not csrf_token:
            return JsonResponse({'mensaje': "CSRF token no encontrado."}, status=403)
        
        carrito_id = request.session.get("carrito_id")
        if not carrito_id:
            nuevo_carrito = Carrito.objects.create()
            request.session["carrito_id"] = nuevo_carrito.id
        else:
            nuevo_carrito = Carrito.objects.get(id=carrito_id)
        
        producto = get_object_or_404(Producto, pk=producto_id)
        if producto.stock > 0:
            carrito_producto, created = CarritoProducto.objects.get_or_create(
                carrito=nuevo_carrito,
                producto=producto,
                defaults={'cantidad': 1}
            )
            if not created:
                if carrito_producto.cantidad < producto.stock:
                    carrito_producto.cantidad += 1
                    carrito_producto.save()
            return JsonResponse({'mensaje': "Producto agregado al carrito"})
        else:
            return JsonResponse({'mensaje': "Producto sin stock"}, status=400)

    
def ver_carrito(request): # Vista para ver el contenido del carrito
    carrito_id = request.session.get("carrito_id") # Se obtiene el id del carrito de la sesión
    if carrito_id: # Si existe un carrito en la sesión
        carrito = Carrito.objects.get(id=carrito_id) # Se obtiene el carrito
        productos_en_carrito = CarritoProducto.objects.filter(carrito=carrito) # Se obtienen los productos del carrito
        productos = [ # Se crea una lista con los productos del carrito
            {'id': cp.producto.id, 'nombre': cp.producto.nombre, 'cantidad': cp.cantidad, 'precio': cp.producto.precioOferta} # Se crea un diccionario con los datos del producto
            for cp in productos_en_carrito # Se recorren los productos del carrito
        ]
        total = sum(cp.cantidad * cp.producto.precioOferta for cp in productos_en_carrito) # Se calcula el total del carrito
        return JsonResponse({'productos': productos, 'total': float(total)}) # Se responde con los productos y el total
    else: # Si no existe un carrito en la sesión
        return JsonResponse({'productos': [], 'total': 0.0}) # Se responde con una lista vacía y total 0.0

@require_POST # Solo se aceptan peticiones POST
def actualizar_carrito(request, producto_id): # Vista para actualizar la cantidad de un producto en el carrito
    try: # Se intenta realizar la operación
        data = json.loads(request.body) # Se obtiene la información del cuerpo de la petición
        cantidad = int(data.get('cantidad', 0)) # Se obtiene la cantidad del producto
        carrito_id = request.session.get("carrito_id") # Se obtiene el id del carrito de la sesión

        if carrito_id: # Si existe un carrito en la sesión
            carrito_producto = get_object_or_404(CarritoProducto, carrito_id=carrito_id, producto_id=producto_id) # Se obtiene el CarritoProducto
            if cantidad > 0 and cantidad <= carrito_producto.producto.stock: # Si la cantidad es mayor a 0 y menor o igual al stock
                carrito_producto.cantidad = cantidad # Se actualiza la cantidad
                carrito_producto.save() # Se guarda el CarritoProducto
            elif cantidad == 0: # Si la cantidad es 0
                carrito_producto.delete() # Se elimina el CarritoProducto
            # Calcular el total del carrito después de actualizar
            productos_en_carrito = CarritoProducto.objects.filter(carrito_id=carrito_id) # Se obtienen los productos del carrito
            total_carrito = sum(item.cantidad * item.producto.precioOferta for item in productos_en_carrito) # Se calcula el total del carrito
            return JsonResponse({'mensaje': 'Cantidad actualizada correctamente', 'totalCarrito': float(total_carrito)}) # Se responde con un mensaje y el total del carrito
        return JsonResponse({'mensaje': 'Error al actualizar el carrito'}, status=400) # Si no existe un carrito en la sesión, se responde con un mensaje de error
    except Exception as e: # Si ocurre un error
        return JsonResponse({'mensaje': str(e)}, status=500) # Se responde con un mensaje de error


@require_POST # Solo se aceptan peticiones POST
def eliminar_del_carrito(request, producto_id): # Vista para eliminar un producto del carrito
    carrito_id = request.session.get("carrito_id") # Se obtiene el id del carrito de la sesión
    if not carrito_id: # Si no existe un carrito en la sesión
        return JsonResponse({'mensaje': "No existe el carrito"}, status=404) # Se responde con un mensaje de error

    try: # Se intenta realizar la operación
        carrito_producto = CarritoProducto.objects.get(carrito_id=carrito_id, producto_id=producto_id) # Se obtiene el CarritoProducto
        carrito_producto.delete() # Se elimina el CarritoProducto
        return JsonResponse({'mensaje': 'Producto eliminado del carrito'}) # Se responde con un mensaje
    except CarritoProducto.DoesNotExist: # Si el CarritoProducto no existe
        return JsonResponse({'mensaje': 'Producto no encontrado en el carrito'}, status=404) # Se responde con un mensaje de error

def construccion(request): 
    return render(request, 'construccion.html')

def herramientas(request):
    return render(request, 'herramientas.html')

def hogar(request):
    return render(request, 'hogar.html')

def piso_y_pared(request):
    return render(request, 'piso-y-pared.html')

def registro(request):
    if request.method == 'POST':
        form = RegistroUsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('formulario_datos')
    else:
        form = RegistroUsuarioForm()
    return render(request, 'registration/registro.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            # Verificar si el usuario ya tiene datos de cliente guardados
            if Pedido.objects.filter(user=user, datos_completados=True).exists():
                pedido = Pedido.objects.filter(user=user, datos_completados=True).first()
                request.session['pedido_id'] = pedido.id
                return redirect('carrito')
            else:
                return redirect('formulario_datos')
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('index')

@login_required
def formulario_datos(request):
    perfil, created = PerfilUsuario.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        form = PedidoForm(request.POST, instance=perfil)
        if form.is_valid():
            form.save()
            # Guardar el pedido en la sesión si se necesita para la confirmación
            pedido, created = Pedido.objects.get_or_create(user=request.user, defaults={
                'rut': perfil.rut,
                'nombre': perfil.nombre,
                'apellidos': perfil.apellidos,
                'email': perfil.email,
                'numero_pedido': f"{random.randint(1, 999):03d}",
                'datos_completados': True,
            })
            request.session['pedido_id'] = pedido.id
            return redirect('carrito')
    else:
        form = PedidoForm(instance=perfil)
    return render(request, 'formulario_datos.html', {'form': form})

@login_required
def carrito(request):
    carrito_id = request.session.get("carrito_id")
    perfil = PerfilUsuario.objects.get(user=request.user)

    if carrito_id:
        carrito = Carrito.objects.get(id=carrito_id)
        productos_en_carrito = CarritoProducto.objects.filter(carrito=carrito)
        productos = [
            {
                'id': cp.producto.id,
                'nombre': cp.producto.nombre,
                'descripcion': cp.producto.descripcion,
                'detalleCompleto': cp.producto.detalleCompleto,
                'precio': cp.producto.precioOferta,
                'cantidad': cp.cantidad,
                'imagen': cp.producto.imagen.url if cp.producto.imagen else '',
                'total': cp.cantidad * cp.producto.precioOferta,
            }
            for cp in productos_en_carrito
        ]
        total = sum(cp['total'] for cp in productos)
        iva = total * Decimal('0.19')
        total_con_iva = total + iva

        contexto = {
            'productos': productos,
            'total': total,
            'iva': iva,
            'total_con_iva': total_con_iva,
            'perfil': perfil  # Incluir perfil en el contexto
        }

Ferremas_APP/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Link Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
  <!-- Link Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Roboto&family=Roboto+Slab&display=swap" rel="stylesheet" />
  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
   
  <!--Título -->
  <title>Ferretería - Ferremas</title>
</head>


<!-- Modal Usuario -->
<div class="modal fade" id="usuarioModal" tabindex="-1" aria-labelledby="usuarioModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content rounded-5">
      <div class="modal-header bg-success rounded-top-5">
        <h2 class="modal-title text-white mx-3" id="usuarioModalLabel">Usuario</h2>
        <button type="button" class="btn-close me-3" data-bs-dismiss="modal" aria-label="Close" style="color: white;"></button>
      </div>
      <div class="modal-body ms-3">
        {% if user.is_authenticated %}
        <p>Hola, {{ user.username }}!</p>
        <a href="{% url 'logout' %}" class="btn btn-danger btn-lg mb-3 px-5" style="font-size: 2rem;">Cerrar sesión</a>
        <a href="{% url 'formulario_datos' %}" class="btn btn-warning btn-lg mb-3 px-5" style="font-size: 2rem;">Modificar datos</a>
        {% else %}
        <a href="{% url 'login' %}" class="btn btn-success btn-lg mb-3 px-5" style="font-size: 2rem;">Iniciar sesión</a>
        <a href="{% url 'registro' %}" class="btn btn-primary btn-lg mb-3 px-5" style="font-size: 2rem;">Registrarse</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<!-- Fin Modal Usuario -->


<!-- Modal Carrito -->
<div class="modal fade" id="carritoModal" tabindex="-1" aria-labelledby="carritoModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content rounded-5">
      <div class="modal-header bg-success rounded-top-5">
        <h2 class="modal-title text-white mx-3" id="carritoModalLabel">Carrito de Compras</h2>
        <button type="button" class="btn-close me-3" data-bs-dismiss="modal" aria-label="Close" style="color: white;"></button>
      </div>
      <div class="modal-body ms-3">
      </div>
      <div class="modal-footer d-flex justify-content-between mx-3">
        <button type="button" class="btn btn-success btn-lg mb-3 px-5" style="font-size: 2rem;" data-bs-dismiss="modal">Seguir comprando</button>
        <button type="button" id="irAPagarBtn" class="btn btn-warning btn-lg mb-3 px-5" style="font-size: 2rem;">Ir a pagar</button>
      </div>
    </div>
  </div>
</div>
<!-- Fin Modal Carrito -->



<body>
  <!-- Oferta Despacho -->
  <section>
    <div class="container-fluid d-flex justify-content-center bg-warning" style="height: 40px">
      <p class="text-black" style="font-size: 2.4rem; font-weight: bold">
        !<strong> APROVECHA</strong> - Despacho gratis en todas tus compras
        sobre $50.000 ¡
      </p>
    </div>
  </section>
  <!-- Fin Oferta Despacho -->

  <!-- Header con navbar -->
  <header class="container-fluid bg-success d-flex align-items-center justify-content-between"
    style="height: 120px; padding-right: 60px">
    <div class="container-fluid">
      <nav class="navbar navbar-expand-md justify-content-between">
        <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'img/Logo-xl.png' %}" alt="Logo" height="80"
            class="d-inline-block align-text-top" /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item me-3 {% if request.path == '/' %}active{% endif %}">
              <a class="nav-link {% if request.path == '/' %}text-warning{% else %}text-white{% endif %}"
                href="{% url 'index' %}">Inicio</a>
            </li>
            <li class="nav-item me-3 {% if request.path == '/construccion/' %}active{% endif %}">
              <a class="nav-link {% if request.path == '/construccion/' %}text-warning{% else %}text-white{% endif %}"
                href="{% url 'construccion' %}">Construcción</a>
            </li>
            <li class="nav-item me-3 {% if request.path == '/herramientas/' %}active{% endif %}">
              <a class="nav-link {% if request.path == '/herramientas/' %}text-warning{% else %}text-white{% endif %}"
                href="{% url 'herramientas' %}">Herramientas</a>
            </li>
            <li class="nav-item me-3 {% if request.path == '/hogar/' %}active{% endif %}">
              <a class="nav-link {% if request.path == '/hogar/' %}text-warning{% else %}text-white{% endif %}"
                href="{% url 'hogar' %}">Hogar</a>
            </li>
            <li class="nav-item me-3 {% if request.path == '/piso_y_pared/' %}active{% endif %}">
              <a class="nav-link {% if request.path == '/piso_y_pared/' %}text-warning{% else %}text-white{% endif %}"
                href="{% url 'piso_y_pared' %}">Piso y Pared</a>
            </li>
          </ul>
        </div>
        <!-- Icono Usuario -->
        <div class="user-icon-container bg-success" style="margin-left: 30px;">
          <button id="icono-usuario" class="btn boton-usuario" data-bs-toggle="modal" data-bs-target="#usuarioModal">
            <img src="{% static 'img/fabrica.gif' %}" alt="Usuario" style="width: 5rem; height: 5rem;">
          </button>
        </div>
      </nav>
    </div>
      <!-- Carrito -->
        <div class="cart-icon-container bg-success" style="margin-left: 20px; padding-right: 50px;">
          <button id="icono-carrito" class="btn boton-carrito position-relative" data-bs-toggle="modal" data-bs-target="#carritoModal">
            <img src="{% static 'img/herramientas.gif' %}" alt="Carrito de Compras" style="width: 5rem; height: 5rem;">
            <span id="cart-count" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
              0
            </span>
          </button>
        </div>  
        <!-- Fin Carrito -->
        
  </header>
  <!-- Fin Header con navbar -->

  <main>

    {% block contenido %}

    {% endblock %}

  </main>

  <!-- PIE DE PÁGINA -->
  <footer class="container-fluid bg-success d-flex justify-content-center align-items-center">
    <div class="container d-flex flex-column align-items-center text-white ">
      <p class="text-center mb-0 ">Ferremas - Ferretería y Construcción © 2024</p>
      <p class="text-center ">Desarrollado por <strong>InnovaTech</strong></p>
    </div>
  </footer>

  <!-- Vínculo JS -->
  <script src="{% static 'js/app.js' %}"></script>
  <!-- Script de Bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"crossorigin="anonymous"></script>
  <!-- Sweet Alert2 -->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</body>
</html>

Ferremas_APP/templates/formulario_datos.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}
<div style="height: 910px;">
    <div class="container bg-secondary bg-opacity-10 rounded-5 pt-5" style="height: 800px; width: 600px; margin-top: 80px;">
        <div class="row mt-5 mb-5 text-uppercase">
            <div class="col text-center mb-5">
                <h1 class="fw-bold" style="font-size: 3.6rem;">Datos del Cliente</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form id="datos-cliente-form" class="formulario-retiro-entrega" method="post" action="">
                    {% csrf_token %}
                    <div class=" mb-5">
                        <label for="id_tipo_entrega" class="form-label mb-5 fs-2">Seleccione el tipo de entrega</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="tipo_entrega" id="tipo_entrega_rt" value="RT" checked>
                            <label class="form-check-label" for="tipo_entrega_rt">Retiro en Tienda</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="tipo_entrega" id="tipo_entrega_dd" value="DD" >
                            <label class="form-check-label" for="tipo_entrega_dd">Despacho a Domicilio (Próximamente)</label>
                        </div>
                    </div>
                    <div class="mb-3 fs-3">
                        <label for="id_rut" class="form-label input-retiro-entrega">Rut</label>
                        {{ form.rut }}
                    </div>
                    <div class="mb-3 fs-3">
                        <label for="id_nombre" class="form-label">Nombre</label>
                        {{ form.nombre }}
                    </div>
                    <div class="mb-3 fs-3">
                        <label for="id_apellidos" class="form-label">Apellidos</label>
                        {{ form.apellidos }}
                    </div>
                    <div class="mb-3 fs-3">
                        <label for="id_email" class="form-label">Correo Electrónico</label>
                        {{ form.email }}
                    </div>
                    <div class="d-flex justify-content-between mt-5">
                        <button type="submit" class="btn btn-success fs-2 btn-lg px-5">Ir al Carrito</button>
                        <a href="{% url 'index' %}" class="btn btn-secondary fs-2 btn-lg px-5">Ir al Home</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const rutInput = document.getElementById('id_rut');
    
    rutInput.addEventListener('input', formatRUT);
    
    function formatRUT() {
        let value = rutInput.value.replace(/\./g, '').replace(/-/g, '');
        if (value.length > 1) {
            value = value.slice(0, -1).replace(/\B(?=(\d{3})+(?!\d))/g, '.') + '-' + value.slice(-1);
        }
        rutInput.value = value;
    }

    // Función para verificar si el carrito tiene productos
    function verificarCarrito() {
        fetch("/ver_carrito/")
            .then(response => response.json())
            .then(data => {
                const irAPagarBtn = document.getElementById('irAPagarBtn');
                if (data.productos.length === 0) {
                    irAPagarBtn.disabled = true;
                } else {
                    irAPagarBtn.disabled = false;
                }
            })
            .catch(error => console.error("Error al verificar el carrito:", error));
    }

    verificarCarrito(); // Llamar a la función al cargar la página
});
</script>

{% endblock %}

Ferremas_APP/templates/pago_exitoso.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container-fuid d-flex justify-content-center align-items-center" style="height: 100vh">
    <div class="container d-flex justify-content-center bg-success-subtle rounded-5 w-25" style="height: 600px; margin-top: 80px; margin-bottom: 80px;">
        <div class="d-flex flex-column align-items-center justify-content-center ">
            <div class="justify-content-center align-items-center">
                <h1 class="mb-5" style="font-size: 3.2rem; font-weight: bold;">Pago Exitoso</h1>
            </div>
            <div class="justify-content-center align-items-center">
                <p class="fs-2 mb-5">Tu pago ha sido procesado exitosamente.</p>
                <p class="fs-2">Detalles del pedido.</p>
                <ul class="fs-2" style="list-style: none;">
                    <li><strong>Número de Pedido: </strong>{{ pedido.numero_pedido }}</li>
                    <li><strong>RUT: </strong>{{ pedido.rut }}</li>
                    <li><strong>Nombre: </strong>{{ pedido.nombre }}</li>
                    <li><strong>Apellidos: </strong>{{ pedido.apellidos }}</li>
                    <li><strong>Correo Electrónico: </strong>{{ pedido.email }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}